name: gado_certo_todo_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  extended_text: ^13.0.0
  flutter_local_notifications: ^17.1.0
  intl: ^0.18.1
  reactive_forms: ^16.1.1
  quickalert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
